# Generated by Django 5.0.7 on 2025-09-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='login_pin',
            field=models.CharField(blank=True, help_text='6-digit PIN for account login', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='transaction_pin',
            field=models.CharField(blank=True, help_text='4-digit PIN for transactions', max_length=128, null=True),
        ),
    ]
