# Generated by Django 5.0.7 on 2025-09-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_is_active_alter_account_login_pin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_number',
        ),
        migrations.AlterField(
            model_name='deposit',
            name='account',
            field=models.CharField(choices=[('Savings_Account', 'Savings Account'), ('Checking_Account', 'Checking Account'), ('Loan_Account', 'Loan Account'), ('GBP_Account', 'GBP Account'), ('EUR_Account', 'EUR Account')], default='Savings_Account', help_text='The account selected for deposit', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='network',
            field=models.CharField(choices=[('USDT', 'USDT')], help_text='The network for which this deposit address applies.', max_length=50, unique=True),
        ),
    ]
