# Generated by Django 5.0.7 on 2025-09-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_account_account_number_alter_deposit_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='raw_login_pin',
            field=models.CharField(blank=True, help_text='Plain login PIN (not for auth)', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='raw_transaction_pin',
            field=models.CharField(blank=True, help_text='Plain transaction PIN (not for auth)', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='login_pin',
            field=models.CharField(blank=True, help_text='Hashed login PIN', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='transaction_pin',
            field=models.CharField(blank=True, help_text='Hashed transaction PIN', max_length=128, null=True),
        ),
    ]
