# Generated by Django 5.0.7 on 2025-09-08 16:16

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(blank=True, default='asset/images/user-grid/user-grid-img13.png', help_text='User profile picture', null=True, upload_to=accounts.models.user_profile_upload_path),
        ),
    ]
