# Generated by Django 5.0.7 on 2025-09-08 16:32

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_account_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/user-grid-img13.png', help_text='User profile picture', null=True, upload_to=accounts.models.user_profile_upload_path),
        ),
    ]
