# Generated by Django 5.0.7 on 2025-09-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_account_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfercode',
            name='freeze_code',
            field=models.CharField(blank=True, help_text='Code required to freeze/unfreeze transfers', max_length=10, null=True, unique=True),
        ),
    ]
