# Generated by Django 5.0.7 on 2025-09-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_transfercode_freeze_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfercode',
            name='imf_code',
        ),
        migrations.AddField(
            model_name='transfercode',
            name='atc_code',
            field=models.CharField(blank=True, help_text='ATC code for international transactions', max_length=10, null=True, unique=True),
        ),
    ]
